# permissions for end users to edit webapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webapp-editor-role
rules:
- apiGroups:
  - webservice.my.domain
  resources:
  - webapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webservice.my.domain
  resources:
  - webapps/status
  verbs:
  - get
